# Generated by Django 3.1.4 on 2021-01-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('email', models.EmailField(max_length=256, verbose_name='Email address')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='Order id')),
                ('fulfillment_status', models.CharField(blank=True, max_length=128, null=True, verbose_name='Fulfillment status')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Order number')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('variant_id', models.IntegerField(blank=True, null=True)),
                ('order_status_url', models.URLField(blank=True, null=True, verbose_name='Order status')),
                ('confirmed', models.BooleanField(blank=True, null=True, verbose_name='Confirmed')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
